baseURL       = "https://arthub.studio/"
languageCode  = "en-us"
title         = "Art Hub Studio LLC"
theme         = ["hugo-embed-pdf-shortcode", "roxo-hugo"]
summarylength = 10

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    identifier = "home"
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    identifier = "about"
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    identifier = "artists"
    name    = "Artists"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    identifier = "blog"
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    identifier = "contact"
    name    = "Contact"
    url     = "https://art-hub-studio-llc.checkoutpage.co/contact-form"
    weight  = 5
  [[menu.nav]]
    identifier = "orders"
    name    = "Orders"
    url     = "https://art-hub-studio-llc.checkoutpage.co/portal"
    weight = 6
  [[menu.nav]]
    identifier = "shop-all"
    name    = "SHOP"
    url     = "shop-all"
    weight  = 7


# Site Params
[params]
  logo = "images/logo.webp"
  logo_footer = "images/logo-footer.webp"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.webp"
  custom_stylesheets = ["css/carousel.css"]   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/14x8ylu"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "Want to become a seller or need customer support? Leave a detailed message here."
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/tony-new-art.webp"
    heading               = "NEW! Artwork by Tony Murchison"
    tagline               = ""
    primary_button        = "See Our Artists"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable       = true
    title        = "Highlighted Artists and Artwork"
    subtitle     = ""
    view_project = "view artist"
    more_works   = "MORE ARTISTS"
    scroll_down  = "scroll down"

  [params.call_to_action]
    enable               = true
    background_image     = "images/backgrounds/cta-background.jpg"
    title                = "Want to sell your art?"
    primary_button       = "Submit Query"
    primary_button_url   = "contact"
    secondary_button     = "Learn more"
    secondary_button_url = "about"

  [params.footer]
    params.footer.qr_print = false
    [params.footer.header]
      title = "Art Hub Studio LLC"
      link = "https://arthub.studio"
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Brooke Schutz<br>2363 James St PMB 1180<br>Syracuse, NY 13206"
      phone   = "607-325-5500"
      email   = "brooke.schutz@arthub.studio"
    # Footer Sitemap
    [params.footer.sitemap]
      title   = "Sitemap"
      [[params.footer.sitemap.link]]
        name = "About Company"
        url  = "about"
      [[params.footer.sitemap.link]]
        name = "Artists"
        url  = "portfolio"
      [[params.footer.sitemap.link]]
        name = "Blog"
        url  = "blog"
      [[params.footer.sitemap.link]]
        name = "Contact"
        url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/art_hub_studio_llc/"
        [[params.footer.social.link]]
          name = "Kofi"
          url  = "https://ko-fi.com/arthubstudiollc"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/company/art-hub-studio-llc/"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/ArtHubStudioLLC/"
      # Footer Other Information
      [params.footer.info]
        title = "Information"
        [[params.footer.info.link]]
          name = "Terms and Conditions"
          url  = "policies/terms"
        [[params.footer.info.link]]
          name = "Privacy Policy"
          url  = "policies/privacy"
        #[[params.footer.info.link]]
         # name = "Shipping Policy"
        #  url  = "shipping"
        [[params.footer.info.link]]
          name = "Cancellation, Return & Refund Policy"
          url  = "policies/refund"
      # Footer Service
      [params.footer.service]
        title       = "We help By:"
        description = "Connecting Artists to Collectors<br>Allowing artists to sell art for free<br>Producing high quality prints"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"

[security]
  enableInlineShortcodes = true

[markup.goldmark.renderer]
  unsafe = true